# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-11 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("base", "0008_auto_20171117_1417")]

    operations = [
        migrations.CreateModel(
            name="MaterializedView",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("updated", models.DateTimeField(null=True)),
            ],
        )
    ]
