# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-19 11:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("base", "0009_materializedview")]

    operations = [
        migrations.AddField(
            model_name="materializedview",
            name="interval",
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AddField(
            model_name="materializedview",
            name="task",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
