# Generated by Django 4.2.28 on 2026-05-28 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_auto_20191219_1237"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="materializedview",
            options={"ordering": ("name",)},
        ),
    ]
