# Generated by Django 5.2.16 on 2026-08-13 19:20

import iso639
import dataclasses

from django.db import migrations, models


def install_languages(apps, schema_editor):
    Language = apps.get_model("base", "Language")
    allowed = {"name", "part3", "part2b", "part2t", "part1"}
    for language in iso639.ALL_LANGUAGES:
        if language.status != "A":
            continue
        kwargs = {k: v for k, v in dataclasses.asdict(language).items() if k in allowed}
        Language.objects.create(**kwargs)


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_alter_materializedview_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512)),
                ("part3", models.CharField(max_length=3)),
                ("part2b", models.CharField(blank=True, max_length=3, null=True)),
                ("part2t", models.CharField(blank=True, max_length=3, null=True)),
                ("part1", models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                "ordering": ("name",),
                "indexes": [
                    models.Index(fields=["part3"], name="base_langua_part3_ce905d_idx"),
                    models.Index(
                        fields=["part2b"], name="base_langua_part2b_62239d_idx"
                    ),
                    models.Index(
                        fields=["part2t"], name="base_langua_part2t_f9979d_idx"
                    ),
                    models.Index(fields=["part1"], name="base_langua_part1_19187d_idx"),
                ],
            },
        ),
        migrations.RunPython(install_languages, migrations.RunPython.noop),
    ]
